# Generated by Django 4.2.6 on 2024-01-19 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0004_alter_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(default='user.jpg', upload_to='image'),
        ),
    ]
