# Generated by Django 4.2.6 on 2024-01-19 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0006_user_name_user_phone_alter_user_bio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='phone',
        ),
    ]
