# Generated by Django 4.2.6 on 2024-01-25 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0010_alter_user_image_alter_user_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='user',
            name='image',
        ),
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='phone',
        ),
    ]
