# Generated by Django 4.2.1 on 2023-11-05 13:22

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_vendor_cover_image_alter_product_vendor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(default='category-image.jpg', upload_to='category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='product-image.jpg', upload_to=core.models.user_directory_path),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='cover_image',
            field=models.ImageField(default='vendor-cover-image.jpg', upload_to=core.models.user_directory_path),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='image',
            field=models.ImageField(default='vendor-image.jpg', upload_to=core.models.user_directory_path),
        ),
    ]
