# Generated by Django 4.2.1 on 2023-11-08 13:11

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_product_mfd_product_product_life_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='image',
            field=models.ImageField(default='vendor.png', upload_to=core.models.user_directory_path),
        ),
    ]
