# Generated by Django 4.2.1 on 2023-11-09 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_productimages_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='mfd',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_life',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_type',
        ),
        migrations.AddField(
            model_name='product',
            name='weight',
            field=models.CharField(blank=True, default='0.7', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='productimages',
            name='images',
            field=models.ImageField(default='product.jpg', upload_to='product-images'),
        ),
    ]
