# Generated by Django 4.2.1 on 2023-11-10 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_product_shipping'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendor',
            name='authentic_rating',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='chat_resp_time',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='days_return',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='shipping_on_time',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='warranty_period',
        ),
        migrations.AddField(
            model_name='product',
            name='life',
            field=models.CharField(blank=True, default='10', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='mfd',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
