# Generated by Django 4.2.6 on 2024-01-13 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_usertracking'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserTracking',
        ),
    ]
