# Generated by Django 4.2.6 on 2024-01-16 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_contactus'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactUs',
        ),
    ]
