# Generated by Django 4.2.6 on 2024-01-19 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_profile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='image',
        ),
    ]
