# Generated by Django 4.2.6 on 2024-01-19 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_remove_profile_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
