# Generated by Django 4.2.6 on 2024-01-25 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_category_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='image',
        ),
    ]
